"""add outbox retry fields

Revision ID: 07260ca935b1
Revises: 37e8e61c3fd1
Create Date: 2026-05-26 18:12:23.117023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07260ca935b1'
down_revision: Union[str, None] = '37e8e61c3fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'attempt_count')
    op.drop_column('incidents', 'last_error')
    op.add_column('outbox_events', sa.Column('attempt_count', sa.Integer(), nullable=False))
    op.add_column('outbox_events', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'last_error')
    op.drop_column('outbox_events', 'attempt_count')
    op.add_column('incidents', sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('attempt_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
