"""create notification tasks table

Revision ID: 0882d83d3dda
Revises: 6dc795bc4be1
Create Date: 2026-05-25 09:27:11.862663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0882d83d3dda'
down_revision: Union[str, None] = '6dc795bc4be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_event_id', name='uq_notification_tasks_source_event_id')
    )
    op.create_index('ix_notification_tasks_incident_id', 'notification_tasks', ['incident_id'], unique=False)
    op.create_index('ix_notification_tasks_status_created_at', 'notification_tasks', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_tasks_status_created_at', table_name='notification_tasks')
    op.drop_index('ix_notification_tasks_incident_id', table_name='notification_tasks')
    op.drop_table('notification_tasks')
    # ### end Alembic commands ###
