"""add outbox retry fields

Revision ID: 37e8e61c3fd1
Revises: 0882d83d3dda
Create Date: 2026-05-26 18:06:41.272683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e8e61c3fd1'
down_revision: Union[str, None] = '0882d83d3dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('attempt_count', sa.Integer(), nullable=False))
    op.add_column('incidents', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'last_error')
    op.drop_column('incidents', 'attempt_count')
    # ### end Alembic commands ###
