"""add correlation id to outbox events

Revision ID: 4c6af5c77999
Revises: 07260ca935b1
Create Date: 2026-05-28 16:26:50.172662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6af5c77999'
down_revision: Union[str, None] = '07260ca935b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('correlation_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'correlation_id')
    # ### end Alembic commands ###
