"""add incident indexes

Revision ID: f22b2011783b
Revises: 127c0e454e40
Create Date: 2026-05-21 11:52:25.873668

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f22b2011783b"
down_revision: Union[str, None] = "127c0e454e40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_incidents_created_at", "incidents", ["created_at"], unique=False)
    op.create_index("ix_incidents_service_name", "incidents", ["service_name"], unique=False)
    op.create_index("ix_incidents_status", "incidents", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_incidents_status", table_name="incidents")
    op.drop_index("ix_incidents_service_name", table_name="incidents")
    op.drop_index("ix_incidents_created_at", table_name="incidents")
    # ### end Alembic commands ###
